DROP TABLE IF EXISTS car;

DROP TABLE IF EXISTS driver;

CREATE TABLE driver (
    driver_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(20) NOT NULL UNIQUE,
    dateStartWork TIMESTAMP NOT NULL,
    salary DECIMAL NOT NULL
);

CREATE TABLE car (
    car_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    model VARCHAR(20) NOT NULL,
    driver_id INT NOT NULL,
    CONSTRAINT car_driver_fk FOREIGN KEY (driver_id) REFERENCES driver(driver_id)
);